all: mergeTime mergeSort insertTime insertSort

mergeTime: mergetime.cpp
	g++ mergetime.cpp -o mergeTime

mergeSort: mergesort.cpp
	g++ mergesort.cpp -o mergeSort

insertTime: inserttime.cpp
	g++ inserttime.cpp -o insertTime

insertSort: insertsort.cpp
	g++ insertsort.cpp -o insertSort

clean:
	rm -f mergeTime mergeSort insertTime insertSort
