all: mergesort3 mergesort3Time

mergesort3: mergesort3.cpp
	g++ mergesort3.cpp -o mergesort3

mergesort3Time: mergesort3time.cpp
	g++ mergesort3time.cpp -o mergesort3Time

clean:
	rm -f mergesort3 mergesort3Time
